spring:
  application:
    name: k-web
  web:
    resources:
      add-mappings: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:k-web
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      schema-locations: classpath:schema/h2.sql

server:
  port: 8080
