DROP TABLE IF EXISTS item;
CREATE TABLE item (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    create_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    price BIGINT,
    count BIGINT,
    name VARCHAR(250) NOT NULL,
    description VARCHAR(2500) NOT NULL,
    category VARCHAR(250) NOT NULL
);
